M48
; DRILL file {KiCad 8.0.2} date 2024-05-12T16:10:17+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-12T16:10:17+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.300
%
G90
G05
T1
X128.27Y-78.74
X128.27Y-106.68
X185.42Y-78.74
X185.42Y-106.68
T2
X139.11Y-84.12
X139.11Y-101.3
M30
